<?php
$sLangName = 'English';

$aLang = array(
  'charset' => 'UTF-8',

  'SHOP_MODULE_GROUP_slider_display' => 'display',
  'SHOP_MODULE_GROUP_slider_navigation' => 'navigation',
  'SHOP_MODULE_GROUP_slider_transitions' => 'transition effects',
  'SHOP_MODULE_GROUP_slider_responsive' => 'responsive behavior',
  'SHOP_MODULE_GROUP_slider_links' => 'links',
  'SHOP_MODULE_slider_autostart' => 'automatically start slideshow',
  'SHOP_MODULE_slider_idle' => 'slideshow delay, in ms',
  'SHOP_MODULE_slider_duration' => 'duration of the transitions, in ms',
  'SHOP_MODULE_slider_direction' => 'direction',
  'SHOP_MODULE_slider_direction_forward' => 'forward',
  'SHOP_MODULE_slider_direction_backward' => 'backward',
  'SHOP_MODULE_slider_orientation' => 'orientation',
  'SHOP_MODULE_slider_orientation_horizontal' => 'horizontal',
  'SHOP_MODULE_slider_orientation_vertical' => 'vertical',
  'SHOP_MODULE_slider_show_arrows' => 'show navigation arrows',
  'SHOP_MODULE_slider_arrow_type' => 'arrow type (integer between 1 and 22)',
  'HELP_SHOP_MODULE_slider_arrow_type' => 'For all available arrow types see <a href="http://www.jssor.com/skins/" target="_blank">www.jssor.com/skins/</a>.',
  'SHOP_MODULE_slider_show_bullets' => 'show navigation bullets',
  'SHOP_MODULE_slider_bullet_type' => 'bullet type (integer between 1 and 21)',
  'HELP_SHOP_MODULE_slider_bullet_type' => 'For all available bullet types see <a href="http://www.jssor.com/skins/" target="_blank">www.jssor.com/skins/</a>.',
  'SHOP_MODULE_slider_transitions_code' => 'code for the transition effect',
  'HELP_SHOP_MODULE_slider_transitions_code' => 'The code for the transition effects can be obtained <a href="http://www.jssor.com/development/tool-slideshow-transition-viewer.html" target="_blank">hier</a>. Please copy the complete content of the input field <em>Transition Code</em> here.<br>To use multiple transitions, generate the <em>Transition Code</em>s as described and paste them here, separated by em>,</em>.',
  'SHOP_MODULE_slider_transitions_random' => 'show transition effects in random order',
  'SHOP_MODULE_slider_show_on_smartphone' => 'show on smartphones',
  'SHOP_MODULE_slider_show_on_tablet' => 'show on tablets',
  'SHOP_MODULE_sPromoBannersizePhone' => 'image size for smartphones',
  'SHOP_MODULE_sPromoBannersizeTablet' => 'image size for tablets',
  'SHOP_MODULE_sPromoBannersize' => 'image size for large displays',
  'SHOP_MODULE_slider_link_whole_slide' => 'use whole slide as a link',
  'HELP_SHOP_MODULE_slider_link_whole_slide' => 'Normally only the title acts as a link. If activated, the whole slide is a link.',
  'BANNER_OXID' => 'OXID',
  'HELP_BANNER_OXID' => 'If you create a CMS snippet with the same OXID, it will be shown on top of the slide. ',
);
